// furnitureDataItems

exports.furnitureDataItems = [
    {
        categoryId: 10,
        name: "Beige Chair",
        type: "Chair",
        dimensionsUnit: "cm",
        dimensions: {
            length: "50",
            width: "50",
            height: "90",
        },
        color: "Beige",
        material: "Fabric",
        price: "60",
        brand: "FurnitureCo",
        unityName: "BeigeChair",
        features: ["Comfortable Seating", "Lightweight", "Elegant Design"],
        weight: "8 kg",
        imageUrl: "https://dzignestatebucket.s3.amazonaws.com/products/BeigeChair.png",
        warranty: "1 year",
        rating: 4.5,
        reviews: 100,
        availability: true,
        tags: ["modern", "comfortable", "lightweight"],
        customizationOptions: null,
        shippingDimensions: {
            length: "55",
            width: "55",
            height: "95",
        },
        shippingWeight: "10 kg",
        deliveryTime: "5-7 business days",
        ecoFriendly: true,
        careInstructions: "Wipe with a soft dry cloth.",
        discount: 5,
        bundleOffers: "Buy 2 Chairs, Get 1 Table at 20% off",
        faq: [
            {
                question: "Does this chair require assembly?",
                answer: "No, the chair comes fully assembled.",
            },
            {
                question: "Is the fabric washable?",
                answer: "Yes, the fabric can be spot cleaned.",
            },
        ],
        countryOfOrigin: "China",
    },
    {
        categoryId: 10,
        name: "Hall Table",
        type: "Table",
        dimensionsUnit: "cm",
        dimensions: {
            length: "120",
            width: "40",
            height: "75",
        },
        color: "Natural Wood",
        material: "Wood",
        price: "60",
        brand: "FurnitureCo",
        unityName: "HallTable",
        features: ["Compact Size", "Durable Material", "Scratch-Resistant Finish"],
        weight: "12 kg",
        imageUrl: "https://dzignestatebucket.s3.amazonaws.com/products/HallTable.png",
        warranty: "1 year",
        rating: 4.6,
        reviews: 85,
        availability: true,
        tags: ["durable", "compact", "stylish"],
        customizationOptions: {
            finishes: ["Glossy", "Matte"],
        },
        shippingDimensions: {
            length: "125",
            width: "45",
            height: "80",
        },
        shippingWeight: "15 kg",
        deliveryTime: "3-5 business days",
        ecoFriendly: true,
        careInstructions: "Clean with a damp cloth. Avoid harsh chemicals.",
        discount: 10,
        bundleOffers: "Buy 1 Table, Get 2 Chairs at 10% off",
        faq: [
            {
                question: "Is this table easy to move?",
                answer: "Yes, it is lightweight and easy to carry.",
            },
            {
                question: "Can it be used outdoors?",
                answer: "It is recommended for indoor use only.",
            },
        ],
        countryOfOrigin: "India",
    },
    {
        categoryId: 10,
        name: "Lunch Table",
        type: "Table",
        dimensionsUnit: "cm",
        dimensions: {
            length: "140",
            width: "80",
            height: "75",
        },
        color: "Brown",
        material: "Solid Wood",
        price: "60",
        brand: "OakLine",
        unityName: "LunchTable",
        features: ["Sturdy Build", "Spacious Surface", "Classic Design"],
        weight: "20 kg",
        imageUrl: "https://dzignestatebucket.s3.amazonaws.com/products/LunchTable.png",
        warranty: "2 years",
        rating: 4.7,
        reviews: 120,
        availability: true,
        tags: ["classic", "durable", "spacious"],
        customizationOptions: {
            finishes: ["Matte", "Natural Polish"],
        },
        shippingDimensions: {
            length: "145",
            width: "85",
            height: "80",
        },
        shippingWeight: "22 kg",
        deliveryTime: "5-7 business days",
        ecoFriendly: false,
        careInstructions: "Wipe with a damp cloth. Avoid prolonged exposure to water.",
        discount: 15,
        bundleOffers: "Buy 1 Table, Get 10% off on matching chairs",
        faq: [
            {
                question: "Can this table seat 6 people?",
                answer: "Yes, it is suitable for 6 people.",
            },
            {
                question: "Does it come pre-assembled?",
                answer: "No, it requires simple assembly.",
            },
        ],
        countryOfOrigin: "USA",
    },
    {
        categoryId: 10,
        name: "Metal Table",
        type: "Table",
        dimensionsUnit: "cm",
        dimensions: {
            length: "120",
            width: "60",
            height: "75",
        },
        color: "Silver",
        material: "Metal",
        price: "60",
        brand: "SteelLine",
        unityName: "MetalTable",
        features: ["Rust-Resistant", "Lightweight", "Modern Design"],
        weight: "15 kg",
        imageUrl: "https://dzignestatebucket.s3.amazonaws.com/products/MetalTable.png",
        warranty: "3 years",
        rating: 4.6,
        reviews: 95,
        availability: true,
        tags: ["modern", "durable", "lightweight"],
        customizationOptions: {
            finishes: ["Matte", "Glossy"],
        },
        shippingDimensions: {
            length: "125",
            width: "65",
            height: "80",
        },
        shippingWeight: "18 kg",
        deliveryTime: "3-5 business days",
        ecoFriendly: true,
        careInstructions: "Clean with a damp cloth and dry immediately.",
        discount: 10,
        bundleOffers: "Buy 1 Metal Table, Get 2 Chairs at 15% off",
        faq: [
            {
                question: "Is this table suitable for outdoor use?",
                answer: "Yes, it is rust-resistant and can be used outdoors.",
            },
            {
                question: "Does it scratch easily?",
                answer: "No, it has a scratch-resistant finish.",
            },
        ],
        countryOfOrigin: "India",
    },
    {
        categoryId: 10,
        name: "Mirror",
        type: "Decor",
        dimensionsUnit: "cm",
        dimensions: {
            length: "100",
            width: "60",
            height: "2",
        },
        color: "Silver",
        material: "Glass with Metal Frame",
        price: "60",
        brand: "ReflectionPro",
        unityName: "Mirror",
        features: ["Frameless Design", "Scratch-Resistant Glass", "Lightweight"],
        weight: "8 kg",
        imageUrl: "https://dzignestatebucket.s3.amazonaws.com/products/Mirror.png",
        warranty: "1 year",
        rating: 4.8,
        reviews: 120,
        availability: true,
        tags: ["decorative", "modern", "sleek"],
        customizationOptions: null,
        shippingDimensions: {
            length: "105",
            width: "65",
            height: "5",
        },
        shippingWeight: "10 kg",
        deliveryTime: "5-7 business days",
        ecoFriendly: true,
        careInstructions: "Clean with glass cleaner and a soft cloth.",
        discount: 5,
        bundleOffers: "Buy 1 Mirror, Get 10% off on matching decor items",
        faq: [
            {
                question: "Can this mirror be wall-mounted?",
                answer: "Yes, it comes with mounting hardware.",
            },
            {
                question: "Is the glass shatterproof?",
                answer: "No, but it is highly durable under normal use.",
            },
        ],
        countryOfOrigin: "China",
    },
    {
        categoryId: 10,
        name: "Pouf",
        type: "Seating",
        dimensionsUnit: "cm",
        dimensions: {
            length: "50",
            width: "50",
            height: "45",
        },
        color: "Gray",
        material: "Fabric with Foam Filling",
        price: "60",
        brand: "CozySeating",
        unityName: "Pouf",
        features: ["Comfortable Padding", "Lightweight", "Durable Fabric"],
        weight: "5 kg",
        imageUrl: "https://dzignestatebucket.s3.amazonaws.com/products/Pouf.png",
        warranty: "1 year",
        rating: 4.7,
        reviews: 80,
        availability: true,
        tags: ["cozy", "lightweight", "stylish"],
        customizationOptions: {
            colors: ["Gray", "Blue", "Beige"],
        },
        shippingDimensions: {
            length: "55",
            width: "55",
            height: "50",
        },
        shippingWeight: "6 kg",
        deliveryTime: "3-5 business days",
        ecoFriendly: true,
        careInstructions: "Spot clean with a damp cloth.",
        discount: 10,
        bundleOffers: "Buy 2 Poufs, Get 1 Matching Rug at 20% off",
        faq: [
            {
                question: "Can this pouf be used as a footrest?",
                answer: "Yes, it is designed for multi-purpose use.",
            },
            {
                question: "Is the cover removable?",
                answer: "No, the cover is fixed.",
            },
        ],
        countryOfOrigin: "Turkey",
    },
    {
        categoryId: 10,
        name: "Stool",
        type: "Seating",
        dimensionsUnit: "cm",
        dimensions: {
            length: "40",
            width: "40",
            height: "45",
        },
        color: "Natural Wood",
        material: "Wood",
        price: "60",
        brand: "SimpleSeating",
        unityName: "Stool",
        features: ["Compact Design", "Lightweight", "Durable"],
        weight: "4 kg",
        imageUrl: "https://dzignestatebucket.s3.amazonaws.com/products/Stool.png",
        warranty: "1 year",
        rating: 4.5,
        reviews: 70,
        availability: true,
        tags: ["portable", "sturdy", "minimalist"],
        customizationOptions: {
            finishes: ["Matte", "Polished"],
        },
        shippingDimensions: {
            length: "45",
            width: "45",
            height: "50",
        },
        shippingWeight: "5 kg",
        deliveryTime: "3-5 business days",
        ecoFriendly: true,
        careInstructions: "Wipe with a damp cloth.",
        discount: 10,
        bundleOffers: "Buy 4 Stools, Get 1 Matching Table at 20% off",
        faq: [
            {
                question: "Is this stool stackable?",
                answer: "Yes, it is designed for stacking.",
            },
            {
                question: "Can it support heavy weight?",
                answer: "Yes, it is sturdy and supports up to 100 kg.",
            },
        ],
        countryOfOrigin: "Vietnam",
    },
    {
        categoryId: 10,
        name: "White Cabinet",
        type: "Storage",
        dimensionsUnit: "cm",
        dimensions: {
            length: "80",
            width: "40",
            height: "100",
        },
        color: "White",
        material: "Wood",
        price: "60",
        brand: "StoragePro",
        unityName: "Whitecabinet",
        features: ["Spacious Storage", "Modern Look", "Scratch-Resistant Finish"],
        weight: "25 kg",
        imageUrl: "https://dzignestatebucket.s3.amazonaws.com/products/Whitecabinet.png",
        warranty: "2 years",
        rating: 4.6,
        reviews: 90,
        availability: true,
        tags: ["modern", "compact", "spacious"],
        customizationOptions: null,
        shippingDimensions: {
            length: "85",
            width: "45",
            height: "110",
        },
        shippingWeight: "28 kg",
        deliveryTime: "5-7 business days",
        ecoFriendly: false,
        careInstructions: "Wipe with a dry cloth. Avoid water exposure.",
        discount: 5,
        bundleOffers: "Buy 2 Cabinets, Get 10% off on matching shelves",
        faq: [
            {
                question: "Is the cabinet easy to assemble?",
                answer: "Yes, it comes with detailed assembly instructions.",
            },
            {
                question: "Does it include a lock?",
                answer: "No, it does not come with a lock.",
            },
        ],
        countryOfOrigin: "China",
    },
    {
        categoryId: 10,
        name: "White Long Cabinet",
        type: "Storage",
        dimensionsUnit: "cm",
        dimensions: {
            length: "160",
            width: "40",
            height: "50",
        },
        color: "White",
        material: "MDF",
        price: "60",
        brand: "StorageLine",
        unityName: "WhiteLongCabinet",
        features: ["Wide Storage Space", "Minimalist Design", "Durable Build"],
        weight: "30 kg",
        imageUrl: "https://dzignestatebucket.s3.amazonaws.com/products/WhiteLongCabinet.png",
        warranty: "2 years",
        rating: 4.7,
        reviews: 85,
        availability: true,
        tags: ["modern", "spacious", "sleek"],
        customizationOptions: null,
        shippingDimensions: {
            length: "165",
            width: "45",
            height: "55",
        },
        shippingWeight: "35 kg",
        deliveryTime: "5-7 business days",
        ecoFriendly: false,
        careInstructions: "Clean with a soft damp cloth.",
        discount: 5,
        bundleOffers: "Buy 1 Long Cabinet, Get 1 Matching Mirror at 20% off",
        faq: [
            {
                question: "Can this cabinet be wall-mounted?",
                answer: "No, it is designed for floor use.",
            },
            {
                question: "Does it have adjustable shelves?",
                answer: "Yes, the shelves are adjustable.",
            },
        ],
        countryOfOrigin: "India",
    },
    {
        categoryId: 10,
        name: "Bench",
        type: "Seating",
        dimensionsUnit: "cm",
        dimensions: {
            length: "120",
            width: "40",
            height: "45",
        },
        color: "Natural Wood",
        material: "Solid Wood",
        price: "60",
        brand: "BenchPro",
        unityName: "Bench",
        features: ["Sturdy Build", "Comfortable Design", "Scratch-Resistant Finish"],
        weight: "20 kg",
        imageUrl: "https://dzignestatebucket.s3.amazonaws.com/products/Bench.png",
        warranty: "2 years",
        rating: 4.8,
        reviews: 110,
        availability: true,
        tags: ["sturdy", "minimalist", "natural"],
        customizationOptions: {
            finishes: ["Polished", "Rustic"],
        },
        shippingDimensions: {
            length: "125",
            width: "45",
            height: "50",
        },
        shippingWeight: "22 kg",
        deliveryTime: "5-7 business days",
        ecoFriendly: true,
        careInstructions: "Clean with a dry cloth.",
        discount: 15,
        bundleOffers: "Buy 1 Bench, Get 1 Matching Table at 10% off",
        faq: [
            {
                question: "Is the bench suitable for outdoor use?",
                answer: "Yes, it is weather-resistant and can be used outdoors.",
            },
            {
                question: "Does it require assembly?",
                answer: "Yes, minimal assembly is required.",
            },
        ],
        countryOfOrigin: "Malaysia",
    },
    {
        categoryId: 10,
        name: "Blue Sofa",
        type: "Seating",
        dimensionsUnit: "cm",
        dimensions: {
            length: "200",
            width: "90",
            height: "85",
        },
        color: "Blue",
        material: "Fabric",
        price: "140",
        brand: "ComfortZone",
        unityName: "BlueSofa",
        features: ["Comfortable Cushions", "Stylish Design", "Durable Frame"],
        weight: "40 kg",
        imageUrl: "https://dzignestatebucket.s3.amazonaws.com/products/BlueSofa.png",
        warranty: "2 years",
        rating: 4.7,
        reviews: 120,
        availability: true,
        tags: ["stylish", "modern", "comfortable"],
        customizationOptions: {
            colors: ["Blue", "Gray", "Black"],
            fabrics: ["Velvet", "Linen"],
        },
        shippingDimensions: {
            length: "205",
            width: "95",
            height: "90",
        },
        shippingWeight: "45 kg",
        deliveryTime: "7-10 business days",
        ecoFriendly: true,
        careInstructions: "Vacuum regularly. Spot clean with mild detergent.",
        discount: 10,
        bundleOffers: "Buy 1 Sofa, Get 2 Cushions at 20% off",
        faq: [
            {
                question: "Does it come assembled?",
                answer: "Yes, it is delivered fully assembled.",
            },
            {
                question: "Are the cushions removable?",
                answer: "Yes, the cushions are removable and washable.",
            },
        ],
        countryOfOrigin: "India",
    },
    {
        categoryId: 10,
        name: "Brown Chair",
        type: "Seating",
        dimensionsUnit: "cm",
        dimensions: {
            length: "70",
            width: "70",
            height: "100",
        },
        color: "Brown",
        material: "Leather",
        price: "80",
        brand: "LuxSeating",
        unityName: "BrownChair",
        features: ["Ergonomic Design", "Premium Leather", "Adjustable Backrest"],
        weight: "15 kg",
        imageUrl: "https://dzignestatebucket.s3.amazonaws.com/products/BrownChair.png",
        warranty: "2 years",
        rating: 4.6,
        reviews: 85,
        availability: true,
        tags: ["premium", "ergonomic", "adjustable"],
        customizationOptions: {
            colors: ["Brown", "Black"],
        },
        shippingDimensions: {
            length: "75",
            width: "75",
            height: "105",
        },
        shippingWeight: "18 kg",
        deliveryTime: "5-7 business days",
        ecoFriendly: false,
        careInstructions: "Wipe with a dry cloth. Avoid sharp objects.",
        discount: 5,
        bundleOffers: "Buy 4 Chairs, Get 1 Table at 15% off",
        faq: [
            {
                question: "Is it suitable for long hours of use?",
                answer: "Yes, the ergonomic design ensures comfort.",
            },
            {
                question: "Does it swivel?",
                answer: "No, this chair does not have a swivel function.",
            },
        ],
        countryOfOrigin: "Malaysia",
    },
    {
        categoryId: 10,
        name: "Brown Sofa",
        type: "Seating",
        dimensionsUnit: "cm",
        dimensions: {
            length: "220",
            width: "95",
            height: "90",
        },
        color: "Brown",
        material: "Leather",
        price: "110",
        brand: "ComfortLine",
        unityName: "BrownSofa",
        features: ["Classic Design", "High-Quality Leather", "Durable Build"],
        weight: "50 kg",
        imageUrl: "https://dzignestatebucket.s3.amazonaws.com/products/BrownSofa.png",
        warranty: "2 years",
        rating: 4.8,
        reviews: 150,
        availability: true,
        tags: ["classic", "luxury", "durable"],
        customizationOptions: null,
        shippingDimensions: {
            length: "225",
            width: "100",
            height: "95",
        },
        shippingWeight: "55 kg",
        deliveryTime: "7-10 business days",
        ecoFriendly: false,
        careInstructions: "Clean with leather conditioner monthly.",
        discount: 15,
        bundleOffers: "Buy 1 Sofa, Get 1 Ottoman at 10% off",
        faq: [
            {
                question: "Does the sofa recline?",
                answer: "No, this sofa is a fixed model.",
            },
            {
                question: "Is it pet-friendly?",
                answer: "Yes, but care should be taken to avoid scratches.",
            },
        ],
        countryOfOrigin: "Vietnam",
    },
    {
        categoryId: 10,
        name: "Brown Table",
        type: "Table",
        dimensionsUnit: "cm",
        dimensions: {
            length: "120",
            width: "60",
            height: "75",
        },
        color: "Brown",
        material: "Wood",
        price: "115",
        brand: "TableTop",
        unityName: "BrownTable",
        features: ["Spacious Surface", "Classic Look", "Scratch-Resistant Finish"],
        weight: "25 kg",
        imageUrl: "https://dzignestatebucket.s3.amazonaws.com/products/BrownTable.png",
        warranty: "1 year",
        rating: 4.5,
        reviews: 70,
        availability: true,
        tags: ["classic", "spacious", "durable"],
        customizationOptions: null,
        shippingDimensions: {
            length: "125",
            width: "65",
            height: "80",
        },
        shippingWeight: "28 kg",
        deliveryTime: "5-7 business days",
        ecoFriendly: true,
        careInstructions: "Clean with a soft damp cloth.",
        discount: 10,
        bundleOffers: "Buy 1 Table, Get 2 Matching Chairs at 15% off",
        faq: [
            {
                question: "Is assembly required?",
                answer: "Yes, minimal assembly is required.",
            },
            {
                question: "Can it support heavy items?",
                answer: "Yes, it supports up to 50 kg.",
            },
        ],
        countryOfOrigin: "India",
    },
    {
        categoryId: 10,
        name: "Media Table",
        type: "Table",
        dimensionsUnit: "cm",
        dimensions: {
            length: "180",
            width: "40",
            height: "50",
        },
        color: "Black",
        material: "MDF",
        price: "180",
        brand: "MediaSpace",
        unityName: "MediaTable",
        features: ["Cable Management System", "Ample Storage Space", "Modern Finish"],
        weight: "35 kg",
        imageUrl: "https://dzignestatebucket.s3.amazonaws.com/products/MediaTable.png",
        warranty: "2 years",
        rating: 4.9,
        reviews: 200,
        availability: true,
        tags: ["modern", "spacious", "functional"],
        customizationOptions: {
            finishes: ["Matte", "Glossy"],
        },
        shippingDimensions: {
            length: "185",
            width: "45",
            height: "55",
        },
        shippingWeight: "40 kg",
        deliveryTime: "7-10 business days",
        ecoFriendly: true,
        careInstructions: "Dust regularly. Avoid water exposure.",
        discount: 20,
        bundleOffers: "Buy 1 Media Table, Get 1 Wall Shelf at 15% off",
        faq: [
            {
                question: "Does it have drawers?",
                answer: "Yes, it has 2 drawers and 1 open shelf.",
            },
            {
                question: "Can it hold a 70-inch TV?",
                answer: "Yes, it supports TVs up to 70 inches.",
            },
        ],
        countryOfOrigin: "China",
    },
    {
        categoryId: 10,
        name: "Shelf Brown",
        type: "Storage",
        dimensionsUnit: "cm",
        dimensions: {
            length: "120",
            width: "30",
            height: "180",
        },
        color: "Brown",
        material: "Wood",
        price: "142",
        brand: "StoragePro",
        unityName: "ShelfBrown",
        features: ["Ample Storage", "Sturdy Build", "Elegant Design"],
        weight: "25 kg",
        imageUrl: "https://dzignestatebucket.s3.amazonaws.com/products/ShelfBrown.png",
        warranty: "2 years",
        rating: 4.6,
        reviews: 90,
        availability: true,
        tags: ["elegant", "spacious", "wooden"],
        customizationOptions: null,
        shippingDimensions: {
            length: "125",
            width: "35",
            height: "185",
        },
        shippingWeight: "30 kg",
        deliveryTime: "7-10 business days",
        ecoFriendly: true,
        careInstructions: "Clean with a soft cloth. Do not use harsh chemicals.",
        discount: 10,
        bundleOffers: "Buy 1 Shelf, Get 1 Set of Bookends at 15% off",
        faq: [
            {
                question: "Is the shelf easy to assemble?",
                answer: "Yes, it comes with easy-to-follow instructions.",
            },
            {
                question: "Can it hold heavy books?",
                answer: "Yes, the shelf can support up to 50 kg.",
            },
        ],
        countryOfOrigin: "India",
    },
    {
        categoryId: 10,
        name: "Small Shelf",
        type: "Storage",
        dimensionsUnit: "cm",
        dimensions: {
            length: "80",
            width: "30",
            height: "100",
        },
        color: "Brown",
        material: "Wood",
        price: "80",
        brand: "CompactStorage",
        unityName: "SmallShelf",
        features: ["Space-Saving", "Simple Design", "Easy to Install"],
        weight: "15 kg",
        imageUrl: "https://dzignestatebucket.s3.amazonaws.com/products/SmallShelf.png",
        warranty: "1 year",
        rating: 4.5,
        reviews: 60,
        availability: true,
        tags: ["compact", "simple", "storage"],
        customizationOptions: null,
        shippingDimensions: {
            length: "85",
            width: "35",
            height: "105",
        },
        shippingWeight: "18 kg",
        deliveryTime: "5-7 business days",
        ecoFriendly: false,
        careInstructions: "Wipe with a damp cloth to clean.",
        discount: 5,
        bundleOffers: "Buy 2 Small Shelves, Get 1 Wall Hook Set at 10% off",
        faq: [
            {
                question: "Can it hold kitchen items?",
                answer: "Yes, it is suitable for both living room and kitchen use.",
            },
            {
                question: "Is it easy to mount?",
                answer: "Yes, it can be mounted easily with included hardware.",
            },
        ],
        countryOfOrigin: "Vietnam",
    },
    {
        categoryId: 10,
        name: "Wooden Cabinet",
        type: "Storage",
        dimensionsUnit: "cm",
        dimensions: {
            length: "120",
            width: "45",
            height: "170",
        },
        color: "Wooden Brown",
        material: "Wood",
        price: "95",
        brand: "WoodCraft",
        unityName: "Cabinet1",
        features: ["Classic Design", "Spacious Storage", "Eco-Friendly Material"],
        weight: "30 kg",
        imageUrl: "https://dzignestatebucket.s3.amazonaws.com/products/Cabinet1.png",
        warranty: "2 years",
        rating: 4.7,
        reviews: 110,
        availability: true,
        tags: ["wooden", "classic", "eco-friendly"],
        customizationOptions: null,
        shippingDimensions: {
            length: "125",
            width: "50",
            height: "175",
        },
        shippingWeight: "35 kg",
        deliveryTime: "7-10 business days",
        ecoFriendly: true,
        careInstructions: "Dust regularly. Avoid harsh chemicals.",
        discount: 12,
        bundleOffers: "Buy 1 Wooden Cabinet, Get 2 Shelves at 15% off",
        faq: [
            {
                question: "Does it have adjustable shelves?",
                answer: "Yes, it has 3 adjustable shelves.",
            },
            {
                question: "Is it sturdy enough for heavy items?",
                answer: "Yes, it can hold up to 60 kg.",
            },
        ],
        countryOfOrigin: "India",
    },
    {
        categoryId: 10,
        name: "Dining Table Round",
        type: "Table",
        dimensionsUnit: "cm",
        dimensions: {
            length: "120",
            width: "120",
            height: "75",
        },
        color: "Brown",
        material: "Wood",
        price: "113",
        brand: "WoodDesigns",
        unityName: "DiningTableRound",
        features: ["Round Shape", "Spacious Surface", "Premium Finish"],
        weight: "35 kg",
        imageUrl: "https://dzignestatebucket.s3.amazonaws.com/products/DiningTableRound.png",
        warranty: "2 years",
        rating: 4.8,
        reviews: 150,
        availability: true,
        tags: ["premium", "spacious", "modern"],
        customizationOptions: null,
        shippingDimensions: {
            length: "125",
            width: "125",
            height: "80",
        },
        shippingWeight: "40 kg",
        deliveryTime: "7-10 business days",
        ecoFriendly: true,
        careInstructions: "Clean with a soft cloth. Polish occasionally.",
        discount: 10,
        bundleOffers: "Buy 1 Dining Table, Get 4 Chairs at 20% off",
        faq: [
            {
                question: "Is the table easy to assemble?",
                answer: "Yes, assembly instructions are included.",
            },
            {
                question: "What is the maximum seating capacity?",
                answer: "It comfortably seats up to 6 people.",
            },
        ],
        countryOfOrigin: "Vietnam",
    },
    {
        categoryId: 10,
        name: "Single Bed Blue",
        type: "Bedroom",
        dimensionsUnit: "cm",
        dimensions: {
            length: "200",
            width: "90",
            height: "50",
        },
        color: "Blue",
        material: "Wood & Fabric",
        price: "140",
        brand: "ComfyBeds",
        unityName: "SingleBedBlue",
        features: ["Comfortable Mattress", "Modern Design", "Durable Frame"],
        weight: "45 kg",
        imageUrl: "https://dzignestatebucket.s3.amazonaws.com/products/SingleBedBlue.png",
        warranty: "2 years",
        rating: 4.7,
        reviews: 95,
        availability: true,
        tags: ["comfortable", "modern", "durable"],
        customizationOptions: {
            colors: ["Blue", "Gray"],
            mattressTypes: ["Memory Foam", "Innerspring"],
        },
        shippingDimensions: {
            length: "205",
            width: "95",
            height: "55",
        },
        shippingWeight: "50 kg",
        deliveryTime: "7-10 business days",
        ecoFriendly: true,
        careInstructions: "Vacuum the mattress regularly. Spot clean the fabric.",
        discount: 15,
        bundleOffers: "Buy 1 Bed, Get 1 Set of Pillows at 20% off",
        faq: [
            {
                question: "Does it include a mattress?",
                answer: "Yes, the bed includes a comfortable mattress.",
            },
            {
                question: "Is it easy to assemble?",
                answer: "Yes, the assembly process is simple and quick.",
            },
        ],
        countryOfOrigin: "China",
    },
    {
        categoryId: 10,
        name: "Wooden Table",
        type: "Table",
        dimensionsUnit: "cm",
        dimensions: {
            length: "120",
            width: "60",
            height: "75",
        },
        color: "Wooden Brown",
        material: "Wood",
        price: "130",
        brand: "WoodDesigns",
        unityName: "TableCoffee",
        features: ["Elegant Wooden Finish", "Durable Surface", "Perfect for Living Room"],
        weight: "30 kg",
        imageUrl: "https://dzignestatebucket.s3.amazonaws.com/products/TableCoffee.png",
        warranty: "1 year",
        rating: 4.7,
        reviews: 200,
        availability: true,
        tags: ["wooden", "modern", "spacious"],
        customizationOptions: null,
        shippingDimensions: {
            length: "125",
            width: "65",
            height: "80",
        },
        shippingWeight: "35 kg",
        deliveryTime: "7-10 business days",
        ecoFriendly: true,
        careInstructions: "Clean with a dry cloth. Avoid liquid cleaners.",
        discount: 10,
        bundleOffers: "Buy 1 Wooden Table, Get 1 Set of Chairs at 20% off",
        faq: [
            {
                question: "Can this table be used for outdoor settings?",
                answer: "It is recommended for indoor use only.",
            },
            {
                question: "Is the table easy to assemble?",
                answer: "Yes, it comes with clear assembly instructions.",
            },
        ],
        countryOfOrigin: "India",
    },
    {
        categoryId: 10,
        name: "Tablend",
        type: "Table",
        dimensionsUnit: "cm",
        dimensions: {
            length: "90",
            width: "60",
            height: "75",
        },
        color: "Brown",
        material: "Wood",
        price: "110",
        brand: "Tablend",
        unityName: "Tablend",
        features: ["Compact Design", "Spacious Surface", "Perfect for Small Spaces"],
        weight: "25 kg",
        imageUrl: "https://dzignestatebucket.s3.amazonaws.com/products/Tablend.png",
        warranty: "1 year",
        rating: 4.5,
        reviews: 120,
        availability: true,
        tags: ["compact", "space-saving", "wooden"],
        customizationOptions: null,
        shippingDimensions: {
            length: "95",
            width: "65",
            height: "80",
        },
        shippingWeight: "28 kg",
        deliveryTime: "5-7 business days",
        ecoFriendly: false,
        careInstructions: "Clean with a soft damp cloth.",
        discount: 5,
        bundleOffers: "Buy 1 Tablend, Get 1 Set of Coasters at 10% off",
        faq: [
            {
                question: "Does it have a drawer for storage?",
                answer: "No, it is a simple, open-space design.",
            },
            {
                question: "Is it easy to assemble?",
                answer: "Yes, it can be assembled in under 30 minutes.",
            },
        ],
        countryOfOrigin: "Vietnam",
    },
    {
        categoryId: 10,
        name: "Wall Shelf",
        type: "Storage",
        dimensionsUnit: "cm",
        dimensions: {
            length: "80",
            width: "20",
            height: "25",
        },
        color: "Brown",
        material: "Wood",
        price: "135",
        brand: "WallStorage",
        unityName: "WallShelf",
        features: ["Wall-Mounted", "Compact and Stylish", "Easy to Install"],
        weight: "5 kg",
        imageUrl: "https://dzignestatebucket.s3.amazonaws.com/products/WallShelf.png",
        warranty: "1 year",
        rating: 4.6,
        reviews: 150,
        availability: true,
        tags: ["compact", "wall-mounted", "stylish"],
        customizationOptions: null,
        shippingDimensions: {
            length: "85",
            width: "25",
            height: "30",
        },
        shippingWeight: "6 kg",
        deliveryTime: "5-7 business days",
        ecoFriendly: true,
        careInstructions: "Dust regularly. Avoid liquid cleaners.",
        discount: 8,
        bundleOffers: "Buy 2 Wall Shelves, Get 1 Set of Wall Hooks at 10% off",
        faq: [
            {
                question: "Can it hold books?",
                answer: "Yes, it can hold books and small decor items.",
            },
            {
                question: "Does it require drilling?",
                answer: "Yes, it requires drilling to mount on the wall.",
            },
        ],
        countryOfOrigin: "India",
    },
    {
        categoryId: 10,
        name: "Ollie Gray Panel Bed",
        type: "Bedroom",
        dimensionsUnit: "cm",
        dimensions: {
            length: "200",
            width: "140",
            height: "50",
        },
        color: "Gray",
        material: "Wood & Fabric",
        price: "200",
        brand: "Ollie",
        unityName: "Bed_Apt_02",
        features: ["Stylish Panel Bed", "Comfortable Mattress Included", "High-Quality Fabric"],
        weight: "50 kg",
        imageUrl: "https://dzignestatebucket.s3.amazonaws.com/products/DoubleBed.png",
        warranty: "2 years",
        rating: 4.9,
        reviews: 300,
        availability: true,
        tags: ["modern", "comfortable", "stylish"],
        customizationOptions: {
            colors: ["Gray", "Beige"],
            mattressTypes: ["Memory Foam", "Innerspring"],
        },
        shippingDimensions: {
            length: "205",
            width: "145",
            height: "55",
        },
        shippingWeight: "55 kg",
        deliveryTime: "7-10 business days",
        ecoFriendly: true,
        careInstructions: "Vacuum the mattress regularly. Spot clean the fabric.",
        discount: 15,
        bundleOffers: "Buy 1 Ollie Bed, Get 2 Pillows at 20% off",
        faq: [
            {
                question: "Does the bed include a mattress?",
                answer: "Yes, the mattress is included.",
            },
            {
                question: "What is the maximum weight capacity?",
                answer: "It can support up to 200 kg.",
            },
        ],
        countryOfOrigin: "China",
    },
    {
        categoryId: 10,
        name: "Brown Chair",
        type: "Seating",
        dimensionsUnit: "cm",
        dimensions: {
            length: "60",
            width: "60",
            height: "85",
        },
        color: "Brown",
        material: "Wood & Fabric",
        price: "180",
        brand: "ComfortSeat",
        unityName: "curveBackChair Variant",
        features: ["Ergonomically Designed", "Premium Fabric", "Comfortable Seating"],
        weight: "15 kg",
        imageUrl: "https://dzignestatebucket.s3.amazonaws.com/products/Chair2.png",
        warranty: "2 years",
        rating: 4.8,
        reviews: 120,
        availability: true,
        tags: ["comfortable", "ergonomic", "premium"],
        customizationOptions: null,
        shippingDimensions: {
            length: "65",
            width: "65",
            height: "90",
        },
        shippingWeight: "20 kg",
        deliveryTime: "5-7 business days",
        ecoFriendly: false,
        careInstructions: "Vacuum clean the fabric. Wipe wooden parts with a dry cloth.",
        discount: 10,
        bundleOffers: "Buy 2 Brown Chairs, Get 1 Sofa Cover at 15% off",
        faq: [
            {
                question: "Is the chair comfortable for long hours?",
                answer: "Yes, it is designed for extended sitting.",
            },
            {
                question: "Can I choose the fabric color?",
                answer: "Currently, the chair is only available in brown.",
            },
        ],
        countryOfOrigin: "India",
    },
    {
        categoryId: 10,
        name: "Master Chair",
        type: "Seating",
        dimensionsUnit: "cm",
        dimensions: {
            length: "70",
            width: "70",
            height: "100",
        },
        color: "Black",
        material: "Wood & Fabric",
        price: "90",
        brand: "MasterSeating",
        unityName: "verticalBackrestChair",
        features: ["Stylish Design", "Comfortable Cushion", "Durable Frame"],
        weight: "12 kg",
        imageUrl: "https://dzignestatebucket.s3.amazonaws.com/products/BigChair.png",
        warranty: "2 years",
        rating: 4.6,
        reviews: 100,
        availability: true,
        tags: ["comfortable", "stylish", "durable"],
        customizationOptions: null,
        shippingDimensions: {
            length: "75",
            width: "75",
            height: "105",
        },
        shippingWeight: "15 kg",
        deliveryTime: "5-7 business days",
        ecoFriendly: false,
        careInstructions: "Clean with a dry cloth. Avoid harsh chemicals.",
        discount: 5,
        bundleOffers: "Buy 2 Master Chairs, Get 1 Sofa Cushion at 10% off",
        faq: [
            {
                question: "Is the chair comfortable for long periods of sitting?",
                answer: "Yes, it is designed for comfort and support.",
            },
            {
                question: "Can I choose different fabric colors?",
                answer: "Currently, the chair is available in a standard fabric color.",
            },
        ],
        countryOfOrigin: "China",
    },
    {
        categoryId: 10,
        name: "Rectangle Table",
        type: "Table",
        dimensionsUnit: "cm",
        dimensions: {
            length: "120",
            width: "60",
            height: "75",
        },
        color: "Brown",
        material: "Wood",
        price: "70",
        brand: "BasicTables",
        unityName: "RectangleTable",
        features: ["Simple Design", "Sturdy Build", "Affordable Price"],
        weight: "25 kg",
        imageUrl: "https://dzignestatebucket.s3.amazonaws.com/products/Table.png",
        warranty: "1 year",
        rating: 4.4,
        reviews: 80,
        availability: true,
        tags: ["simple", "sturdy", "affordable"],
        customizationOptions: null,
        shippingDimensions: {
            length: "125",
            width: "65",
            height: "80",
        },
        shippingWeight: "30 kg",
        deliveryTime: "5-7 business days",
        ecoFriendly: false,
        careInstructions: "Clean with a damp cloth. Avoid using abrasive cleaners.",
        discount: 10,
        bundleOffers: "Buy 1 Rectangle Table, Get 1 Chair at 15% off",
        faq: [
            {
                question: "Is the table easy to assemble?",
                answer: "Yes, it comes with simple assembly instructions.",
            },
            {
                question: "Does it have storage compartments?",
                answer: "No, it is a simple, open design.",
            },
        ],
        countryOfOrigin: "India",
    },
    {
        categoryId: 10,
        name: "Dresser",
        type: "Storage",
        dimensionsUnit: "cm",
        dimensions: {
            length: "90",
            width: "40",
            height: "80",
        },
        color: "Wooden",
        material: "Wood",
        price: "60",
        brand: "StorageMaster",
        unityName: "Dresser",
        features: ["Spacious Drawers", "Stylish Design", "Perfect for Bedrooms"],
        weight: "15 kg",
        imageUrl: "https://dzignestatebucket.s3.amazonaws.com/products/Dresser.png",
        warranty: "1 year",
        rating: 4.5,
        reviews: 110,
        availability: true,
        tags: ["storage", "stylish", "wooden"],
        customizationOptions: null,
        shippingDimensions: {
            length: "95",
            width: "45",
            height: "85",
        },
        shippingWeight: "18 kg",
        deliveryTime: "7-10 business days",
        ecoFriendly: true,
        careInstructions: "Wipe with a dry cloth. Avoid abrasive cleaners.",
        discount: 5,
        bundleOffers: "Buy 1 Dresser, Get 1 Set of Drawer Organizers at 15% off",
        faq: [
            {
                question: "Can the dresser be assembled easily?",
                answer: "Yes, the dresser comes with easy-to-follow assembly instructions.",
            },
            {
                question: "Does it have a locking mechanism?",
                answer: "No, the dresser does not come with a lock.",
            },
        ],
        countryOfOrigin: "India",
    },
    {
        categoryId: 10,
        name: "Dresser Closet",
        type: "Storage",
        dimensionsUnit: "cm",
        dimensions: {
            length: "120",
            width: "60",
            height: "180",
        },
        color: "White",
        material: "Wood & Fabric",
        price: "90",
        brand: "ClosetDesigns",
        unityName: "DresserCloset",
        features: ["Ample Storage Space", "Durable Build", "Multi-Purpose Use"],
        weight: "25 kg",
        imageUrl: "https://dzignestatebucket.s3.amazonaws.com/products/DresserCloset.png",
        warranty: "2 years",
        rating: 4.6,
        reviews: 90,
        availability: true,
        tags: ["storage", "multi-purpose", "white"],
        customizationOptions: null,
        shippingDimensions: {
            length: "125",
            width: "65",
            height: "185",
        },
        shippingWeight: "28 kg",
        deliveryTime: "7-10 business days",
        ecoFriendly: false,
        careInstructions: "Wipe with a damp cloth. Avoid wetting fabric.",
        discount: 8,
        bundleOffers: "Buy 1 Dresser Closet, Get 1 Set of Storage Bins at 10% off",
        faq: [
            {
                question: "Does this dresser closet have adjustable shelves?",
                answer: "Yes, the shelves are adjustable to fit your needs.",
            },
            {
                question: "Can it be used as a wardrobe?",
                answer: "Yes, it is versatile and can be used as a wardrobe or a storage unit.",
            },
        ],
        countryOfOrigin: "China",
    },
    {
        categoryId: 10,
        name: "Hall Sofa",
        type: "Seating",
        dimensionsUnit: "cm",
        dimensions: {
            length: "200",
            width: "80",
            height: "90",
        },
        color: "Gray",
        material: "Fabric",
        price: "120",
        brand: "HallFurnish",
        unityName: "HallSofa",
        features: ["Comfortable Seating", "Stylish and Modern", "Spacious for 3 People"],
        weight: "40 kg",
        imageUrl: "https://dzignestatebucket.s3.amazonaws.com/products/HallSofa.png",
        warranty: "2 years",
        rating: 4.8,
        reviews: 150,
        availability: true,
        tags: ["sofa", "comfortable", "modern"],
        customizationOptions: null,
        shippingDimensions: {
            length: "210",
            width: "85",
            height: "95",
        },
        shippingWeight: "45 kg",
        deliveryTime: "7-10 business days",
        ecoFriendly: true,
        careInstructions: "Vacuum clean the fabric. Wipe down with a damp cloth.",
        discount: 10,
        bundleOffers: "Buy 1 Hall Sofa, Get 2 Throw Pillows at 15% off",
        faq: [
            {
                question: "How many people does this sofa seat?",
                answer: "It seats up to 3 people comfortably.",
            },
            {
                question: "Is the fabric removable?",
                answer: "No, the fabric is not removable but is easy to clean.",
            },
        ],
        countryOfOrigin: "India",
    },
    {
        categoryId: 10,
        name: "Rack Big",
        type: "Storage",
        dimensionsUnit: "cm",
        dimensions: {
            length: "150",
            width: "45",
            height: "180",
        },
        color: "Black",
        material: "Metal",
        price: "110",
        brand: "RackMasters",
        unityName: "RackBig",
        features: ["Heavy-Duty Rack", "Large Storage Space", "Sturdy Metal Construction"],
        weight: "35 kg",
        imageUrl: "https://dzignestatebucket.s3.amazonaws.com/products/RackBig.png",
        warranty: "2 years",
        rating: 4.7,
        reviews: 120,
        availability: true,
        tags: ["storage", "metal", "heavy-duty"],
        customizationOptions: null,
        shippingDimensions: {
            length: "155",
            width: "50",
            height: "185",
        },
        shippingWeight: "40 kg",
        deliveryTime: "7-10 business days",
        ecoFriendly: false,
        careInstructions: "Wipe with a damp cloth. Do not use abrasive materials.",
        discount: 12,
        bundleOffers: "Buy 1 Rack Big, Get 1 Set of Storage Boxes at 20% off",
        faq: [
            {
                question: "Is the rack easy to assemble?",
                answer: "Yes, it is easy to assemble with the provided instructions.",
            },
            {
                question: "Can this rack hold heavy items?",
                answer: "Yes, it is designed to hold up to 100 kg of weight.",
            },
        ],
        countryOfOrigin: "China",
    },
    {
        categoryId: 10,
        name: "Study Table With PC",
        type: "Furniture",
        dimensionsUnit: "cm",
        dimensions: {
            length: "120",
            width: "70",
            height: "75",
        },
        color: "Black",
        material: "Wood & Metal",
        price: "130",
        brand: "StudyPro",
        unityName: "StudytableWithPC",
        features: ["Integrated PC Storage", "Sturdy Build", "Ideal for Study Spaces"],
        weight: "30 kg",
        imageUrl: "https://dzignestatebucket.s3.amazonaws.com/products/StudytableWithPC.png",
        warranty: "1 year",
        rating: 4.7,
        reviews: 95,
        availability: true,
        tags: ["study", "furniture", "modern"],
        customizationOptions: null,
        shippingDimensions: {
            length: "125",
            width: "75",
            height: "80",
        },
        shippingWeight: "35 kg",
        deliveryTime: "7-10 business days",
        ecoFriendly: true,
        careInstructions: "Wipe with a dry cloth. Avoid excessive moisture.",
        discount: 5,
        bundleOffers: "Buy 1 Study Table, Get 1 Set of Keyboard Trays at 10% off",
        faq: [
            {
                question: "Can I store my PC in this table?",
                answer: "Yes, the table has dedicated storage space for a PC.",
            },
            {
                question: "Is the table easy to assemble?",
                answer: "Yes, the table comes with clear assembly instructions.",
            },
        ],
        countryOfOrigin: "India",
    },
    {
        categoryId: 10,
        name: "Cabinet",
        type: "Storage",
        dimensionsUnit: "cm",
        dimensions: {
            length: "120",
            width: "60",
            height: "180",
        },
        color: "Wooden",
        material: "Wood",
        price: "132",
        brand: "StorageMaster",
        unityName: "Cabinet",
        features: ["Spacious Design", "Durable Build", "Perfect for Storing Clothes and Other Items"],
        weight: "40 kg",
        imageUrl: "https://dzignestatebucket.s3.amazonaws.com/products/Cabinet.png",
        warranty: "1 year",
        rating: 4.6,
        reviews: 95,
        availability: true,
        tags: ["storage", "wooden", "durable"],
        customizationOptions: null,
        shippingDimensions: {
            length: "125",
            width: "65",
            height: "185",
        },
        shippingWeight: "43 kg",
        deliveryTime: "7-10 business days",
        ecoFriendly: true,
        careInstructions: "Wipe with a dry cloth.",
        discount: 5,
        bundleOffers: "Buy 1 Cabinet, Get 1 Set of Drawer Organizers at 10% off",
        faq: [
            {
                question: "Can I use this cabinet for storing books?",
                answer: "Yes, the cabinet is versatile and can store books, clothes, or other items.",
            },
            {
                question: "Is it easy to assemble?",
                answer: "Yes, the cabinet comes with easy-to-follow assembly instructions.",
            },
        ],
        countryOfOrigin: "India",
    },
    {
        categoryId: 10,
        name: "Closet",
        type: "Storage",
        dimensionsUnit: "cm",
        dimensions: {
            length: "150",
            width: "60",
            height: "180",
        },
        color: "White",
        material: "Wood & Fabric",
        price: "154",
        brand: "ClosetDesigns",
        unityName: "Closet",
        features: ["Large Storage Space", "Elegant Design", "Perfect for Bedroom or Living Room"],
        weight: "45 kg",
        imageUrl: "https://dzignestatebucket.s3.amazonaws.com/products/Closet.png",
        warranty: "2 years",
        rating: 4.7,
        reviews: 110,
        availability: true,
        tags: ["storage", "closet", "modern"],
        customizationOptions: null,
        shippingDimensions: {
            length: "155",
            width: "65",
            height: "185",
        },
        shippingWeight: "48 kg",
        deliveryTime: "7-10 business days",
        ecoFriendly: false,
        careInstructions: "Wipe with a damp cloth. Avoid excessive moisture.",
        discount: 7,
        bundleOffers: "Buy 1 Closet, Get 1 Set of Closet Organizers at 15% off",
        faq: [
            {
                question: "Can this closet be used for a living room?",
                answer: "Yes, it has a versatile design suitable for both bedrooms and living rooms.",
            },
            {
                question: "Is the fabric durable?",
                answer: "Yes, the fabric used in this closet is strong and built to last.",
            },
        ],
        countryOfOrigin: "China",
    },
];